{% set name = "eigency" %}
{% set version = "3.4.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/e/eigency/eigency-{{ version }}.tar.gz
  sha256: 691f9221152858bce0a398721f048cc10b869a179207b3384b4e6b8da25193dc
  # url: https://github.com/wouterboomsma/eigency/archive/refs/tags/{{ version }}.tar.gz
  # sha256: a08d1025c3eef8f48c77520259d89ba6bf7d9d348110648e1331ad86a737ec14
  # patches:
  #   - version_{{ version }}.patch

build:
  script_env:
    - EIGEN_INC=%PREFIX%\Library\include\eigen3  # [win]
    - EIGEN_INC=${PREFIX}/include/eigen3  # [unix]
  script: {{ PYTHON }} -m pip install --no-deps . -vv
  number: 5

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - setuptools-scm
    - cython
    - numpy
    - eigen >=3.2,<4
  run:
    - python

test:
  imports:
    - eigency.conversions
    - eigency.core

about:
  home: https://github.com/wouterboomsma/eigency
  summary: Cython interface between the numpy arrays and the Matrix/Array classes of the Eigen C++ library
  description: |
    Eigency is a Cython interface between Numpy arrays and Matrix/Array
    objects from the Eigen C++ library. It is intended to simplify the
    process of writing C++ extensions using the Eigen library. Eigency is
    designed to reuse the underlying storage of the arrays when passing data
    back and forth, and will thus avoid making unnecessary copies whenever
    possible. Only in cases where copies are explicitly requested by your
    C++ code will they be made.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  # The doc_url and dev_url are optional.
  dev_url: https://github.com/wouterboomsma/eigency

extra:
  recipe-maintainers:
    - fbordeu
    - casenave
