{% set name = "eigency" %}
{% set version = "3.4.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/wouterboomsma/eigency/archive/refs/tags/{{ version }}.tar.gz
  sha256: a428eae00fc0b2c116b9ce865f758d4d646d8dd8a07f03734af3e8030f4f4102
  patches:
    - 0001-User-can-use-system-eigen.patch

build:
  script_env:
    - EIGEN_INC=%PREFIX%\Library\include\eigen3  # [win]
    - EIGEN_INC=${PREFIX}/include/eigen3  # [unix]
  script: {{ PYTHON }} -m pip install --no-deps . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - cython
    - numpy =1.21  # [py==38]
    - numpy =1.21  # [py==39]
    - numpy =1.21  # [py==310]
    - numpy =1.23.4  # [py==311]
    - eigen >=3.2,<4
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - eigency.conversions
    - eigency.core

about:
  home: https://github.com/wouterboomsma/eigency
  summary: Cython interface between the numpy arrays and the Matrix/Array classes of the Eigen C++ library
  description: |
    Eigency is a Cython interface between Numpy arrays and Matrix/Array
    objects from the Eigen C++ library. It is intended to simplify the
    process of writing C++ extensions using the Eigen library. Eigency is
    designed to reuse the underlying storage of the arrays when passing data
    back and forth, and will thus avoid making unnecessary copies whenever
    possible. Only in cases where copies are explicitly requested by your
    C++ code will they be made.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  # The doc_url and dev_url are optional.
  dev_url: https://github.com/wouterboomsma/eigency

extra:
  recipe-maintainers:
    - fbordeu
    - casenave
